### ISSUE TITLE
The specified type for the complex property is not a complex type.

### ISSUE THREAD

**Issue by LonghornTaco** [object/MongOData#24]
When I connect to one of my Mongo databases, I get this error when trying to call the data service:
![image](https://cloud.githubusercontent.com/assets/5770420/10534130/3933429e-7399-11e5-83c1-49995b602fde.png)

Here's the stack trace:
 at DataServiceProvider.DSPMetadata.AddComplexProperty(ResourceType resourceType, String name, ResourceType complexType)
   at Mongo.Context.MongoMetadataCache.AddComplexProperty(ResourceType resourceType, String propertyName, ResourceType propertyType)
   at Mongo.Context.MongoMetadata.AddDocumentProperty(MongoContext context, String collectionName, ResourceType collectionType, String propertyName, BsonElement element, Boolean isCollection)
   at Mongo.Context.MongoMetadata.AddResourceProperty(MongoContext context, String collectionName, ResourceType collectionType, BsonElement element, Boolean treatObjectIdAsKey)
   at Mongo.Context.MongoMetadata.RegisterResourceProperty(MongoContext context, ResourceType resourceType, BsonElement element)
   at Mongo.Context.MongoMetadata.RegisterDocumentProperty(MongoContext context, ResourceType resourceType, BsonElement element)
   at Mongo.Context.MongoMetadata.UpdateResourceSet(MongoContext context, ResourceSet resourceSet, BsonDocument document)
   at Mongo.Context.MongoMetadata.PopulateMetadataFromCollection(MongoContext context, String collectionName, ResourceSet resourceSet)
   at Mongo.Context.MongoMetadata.PopulateMetadata(MongoContext context)
   at Mongo.Context.MongoMetadata..ctor(String connectionString, Metadata metadata)
   at Mongo.Context.MongoDataServiceBase`2.<.ctor>b__1(String x)
   at Mongo.Context.MongoDataServiceBase`2..ctor(String connectionString, MongoConfiguration mongoConfiguration)
   at Mongo.Context.Queryable.MongoQueryableDataService..ctor(String connectionString, MongoConfiguration mongoConfiguration)
   at MongODataTest.MongoDataService..ctor() in c:\Projects\Sandbox\MongODataTest\MongODataTest\MongoDataService.cs:line 12
   at CreateMongODataTest.MongoDataService()
   at System.ServiceModel.Dispatcher.InstanceProvider.GetInstance(InstanceContext instanceContext, Message message)
   at System.ServiceModel.Dispatcher.InstanceBehavior.GetInstance(InstanceContext instanceContext, Message request)
   at System.ServiceModel.InstanceContext.GetServiceInstance(Message message)
   at System.ServiceModel.Dispatcher.InstanceBehavior.EnsureServiceInstance(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

I was able to connect to a different database, but the one I want the most throws this error.

Thoughts?

**Comment by object** [comment]
Hi,
Here's the code that raises the exception:

if (complexType.ResourceTypeKind != ResourceTypeKind.ComplexType)
{
    throw new ArgumentException("The specified type for the complex property is not a complex type.");
}

It's hard to say what kind of data might cause this but perhaps you can debug it find out.

**Comment by LonghornTaco** [comment]
Looks like it's failing on the Lease property:

![image](https://cloud.githubusercontent.com/assets/5770420/10554398/d9d70d86-7428-11e5-889f-fded69675fff.png)

Viewing with Robomongo:
![image](https://cloud.githubusercontent.com/assets/5770420/10554384/b8d04260-7428-11e5-9910-c5b964e95639.png)

**Comment by object** [comment]
Do you have a small database that you can share so I could try to reproduce the issue?

**Comment by LonghornTaco** [comment]
Here's a mongodump of the database and collection I'm trying to get data from.

**Comment by object** [comment]
Thanks, I will have a look at it.

**Comment by LonghornTaco** [comment]
Any luck?

**Comment by object** [comment]
Sorry, didn't have time to investigate yet (was busywith work and other open source project). Hope to check this out in the next few days.

**Comment by object** [comment]
Hello again,
I believed the issue is fixed now, pushed in the package 1.3.0. Please have check it out.
